baseurl = "/"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
enableGitInfo = true
googleAnalytics = ""
languageCode = "en-us"
theme = "syna"
title = "Okkur - Syna"
version = "0.17.3"
[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]
[markup.goldmark.renderer]
unsafe = true
[[menu.footer_social]]
name = "facebook"
pre = "fab fa-facebook-f"
url = "https://www.facebook.com/VivreVersailles.ec"
weight = 1
[[menu.footer_social]]
name = "instagram"
pre = "fab fa-instagram"
url = "https://www.instagram.com/vivre_versailles"
weight = 4
[[menu.footer_social]]
name = "twitter"
pre = "fab fa-twitter"
url = "https://twitter.com/EcologieVivre"
weight = 3
[[menu.footer_social]]
name = "youtube"
pre = "fab fa-youtube"
url = "https://www.youtube.com/playlist?list=PLBDJoQ5JUmG3vkh-tdzbDsiB4VQAgGT8C"
weight = 2
[[menu.main]]
name = "Articles"
url = "/articles"
weight = 6
[[menu.main]]
name = "Équipe"
url = "/equipe"
weight = 5
[[menu.main]]
name = "Campagne"
url = "/campagne"
weight = 4
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3
[[menu.main]]
name = "Agenda"
url = "/agenda"
weight = 2
[[menu.main]]
name = "Accueil"
url = "/"
weight = 1
[outputs]
home = ["HTML", "JSON"]
[params]
description = "Open Source Theme for your next project"
name = "Okkur Labs"
[params.analytics.piwik]
[params.colors]
danger = "#dc1200"
dark = "#343a40"
info = "#00c9dc"
light = "#f8f9fa"
primary = "#00838F"
secondary = "#868e96"
success = "#008f54"
warning = "#fdf314"
[params.custom]
favicon = "favicon.ico"
favicon_ico_sizes = "16x16 32x32"
favicon_png = "favicon.png"
favicon_svg = "favicon.svg"
[params.fontawesome]
disabled = false
pro = false
[params.style]
